# PROTOTYPE — throwaway: 剧照 → Matrix 字形亮度场转换(方案 A 管线 v2:抠形+描边+归一)
# 用法: python _img2glyph.py
# v2 工序:网格化 → 阈值剪影 → 形态学 close/open → bbox 收紧(+1 格边距) →
#          内部亮度分位数归一(1–4 档) → 轮廓格提 4 档 → 药丸挖除
# 输出: hands-data.js(const HANDS = {...})
from PIL import Image, ImageOps
import json, os

SRC = r"C:\Users\zyf\Desktop\红蓝药丸-6809081929658.png"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "hands-data.js")

CROPS = {"left": (0, 0, 148, 168), "right": (152, 0, 300, 168)}
GRID_W = 56
CHAR_ASPECT = 0.5
BG_T = {"left": 40, "right": 52}  # 剪影阈值(左手在剧照里更暗,单列阈值防轮廓被吃)
MARGIN = 1           # bbox 外扩格数
PILL_RX_MAX = 4.0    # 药丸挖除半径上限(格),防挖出大洞

# 药丸(全图坐标,硬标定;换素材重跑时重标定)
PILL_FULL = {"left": (84, 83, 22, 16), "right": (229, 83, 20, 14)}  # cx, cy, w, h

def dilate(m, W, H):
    return [[any(m[yy][xx] for yy in range(max(0, y-1), min(H, y+2)) for xx in range(max(0, x-1), min(W, x+2)))
             for x in range(W)] for y in range(H)]

def erode(m, W, H):
    return [[all(m[yy][xx] for yy in range(max(0, y-1), min(H, y+2)) for xx in range(max(0, x-1), min(W, x+2)))
             for x in range(W)] for y in range(H)]

def convert(img, side, crop):
    W, H = img.size
    gh = max(1, round(GRID_W * (H / W) * CHAR_ASPECT))
    g = img.resize((GRID_W, gh), Image.LANCZOS)
    px = g.load()
    gray = [[px[x, y] for x in range(GRID_W)] for y in range(gh)]

    # 1) 剪影 + 形态学(close 填缝 → open 去斑)
    m = [[gray[y][x] >= BG_T[side] for x in range(GRID_W)] for y in range(gh)]
    m = erode(dilate(m, GRID_W, gh), GRID_W, gh)
    m = dilate(erode(m, GRID_W, gh), GRID_W, gh)

    # 2) bbox 收紧(+MARGIN)
    ys = [y for y in range(gh) for x in range(GRID_W) if m[y][x]]
    xs = [x for y in range(gh) for x in range(GRID_W) if m[y][x]]
    if not xs:
        raise SystemExit(f"{side}: 剪影为空,调阈值")
    x0, x1 = max(0, min(xs) - MARGIN), min(GRID_W, max(xs) + 1 + MARGIN)
    y0, y1 = max(0, min(ys) - MARGIN), min(gh, max(ys) + 1 + MARGIN)
    tw, th = x1 - x0, y1 - y0

    # 3) 内部亮度分位数归一 → 1–4 档
    interior = sorted(gray[y][x] for y in range(y0, y1) for x in range(x0, x1) if m[y][x])
    def level(v):
        q = sum(1 for t in interior if t <= v) / len(interior)  # 近似分位(小网格够用)
        return 1 if q < 0.45 else 2 if q < 0.75 else 3 if q < 0.93 else 4

    # 4) 药丸格坐标(全图 → 裁剪图 → 网格 → 收紧后网格)
    cx, cy, pw, ph = PILL_FULL[side]
    gx = (cx - crop[0]) / W * GRID_W - x0
    gy = (cy - crop[1]) / H * gh - y0
    pill = {"x": round(gx, 2), "y": round(gy, 2),
            "rx": min(PILL_RX_MAX, max(1.2, pw / W * GRID_W * 0.8)), "ry": max(1.0, ph / H * gh * 1.1)}

    rows = []
    for y in range(y0, y1):
        row = []
        for x in range(x0, x1):
            if not m[y][x]:
                row.append(0); continue
            # 药丸挖除
            if abs(x - x0 - gx) <= pill["rx"] and abs(y - y0 - gy) <= pill["ry"]:
                row.append(0); continue
            # 轮廓格:四邻有空 → 4 档描边
            edge = (x == 0 or x == GRID_W-1 or y == 0 or y == gh-1 or
                    not m[y][x-1] or not m[y][x+1] or not m[y-1][x] or not m[y+1][x])
            row.append(4 if edge else level(gray[y][x]))
        rows.append(row)
    return {"w": tw, "h": th, "levels": rows, "pill": pill}

img = ImageOps.grayscale(Image.open(SRC))
img = ImageOps.autocontrast(img, cutoff=2)
data = {}
for side, box in CROPS.items():
    data[side] = convert(img.crop(box), side, box)

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// PROTOTYPE — generated by _img2glyph.py,勿手改\nconst HANDS = ")
    json.dump(data, f, separators=(",", ":"))
    f.write(";\n")
for side in data:
    d = data[side]
    filled = sum(1 for r in d["levels"] for v in r if v > 0)
    print(side, "grid", d["w"], "x", d["h"], "filled", filled, "pill", d["pill"])
